sleep

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -72,13 +72,25 @@ jobs:
       - name: Install requirements
         run: pip install -r scripts/python/requirements.txt
 
-      - name: Validate labels
+      - name: Sleeeeep
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          REPOSITORY: ${{ env.KYMA_ENVIRONMENT_BROKER_REPO }}
-          NAME: ${{ inputs.name }}
-        run: python3 scripts/python/release_label_validator.py
+          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
+        run: |
+          sleep 300
+          gh api repos/MarekMichali/kyma-environment-broker/commits/main -q '.sha'
+          echo "Workflow sha: ${{ github.sha }}"
+          if [ $(git tag -l ${{ inputs.name }}) ]; then
+            echo "::error ::Tag ${{ inputs.name }} already exists"
+            exit 1
+          fi
 
-  run-unit-tests:
-    name: Unit tests, go mod tidy
-    uses: "./.github/workflows/run-unit-tests-reusable.yaml"
+  #    - name: Validate labels
+   #     env:
+    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+     #     REPOSITORY: ${{ env.KYMA_ENVIRONMENT_BROKER_REPO }}
+      #    NAME: ${{ inputs.name }}
+       # run: python3 scripts/python/release_label_validator.py
+
+#  run-unit-tests:
+ #   name: Unit tests, go mod tidy
+  #  uses: "./.github/workflows/run-unit-tests-reusable.yaml"
